{% set name = "types-redis" %}
{% set version = "4.6.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-redis-{{ version }}.tar.gz
  sha256: 1254d525de7a45e2efaacb6969e67ad1dd5cc359a092022200583a3f04868669

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/redis-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for redis
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
